# Generated by Django 3.2.6 on 2022-02-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
