# Generated by Django 3.2.6 on 2022-02-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Был онлайн'),
        ),
    ]
