# Generated by Django 3.2.6 on 2022-02-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='left_handed',
            field=models.BooleanField(default=False),
        ),
    ]
