# Generated by Django 4.0.1 on 2022-02-01 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
        migrations.AddField(
            model_name='room',
            name='participant_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_1', to=settings.AUTH_USER_MODEL, verbose_name='Участник 1'),
        ),
        migrations.AddField(
            model_name='room',
            name='participant_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_2', to=settings.AUTH_USER_MODEL, verbose_name='Участник 2'),
        ),
    ]
